apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: default
            name: infisical-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: default
            name: infisical-auth-credentials
      secretsScope:
        projectSlug: taotec-iv-vb
        environmentSlug: prod
        secretsPath: /
      hostAPI: https://app.infisical.com